#!/bin/bash

# This software is provided "as-is" and without warranty.
#
# It is licensed under the Creative Commons Attribution-ShareAlike 4.0 International license.
#
# If redistributing, credit Murdo B. Maclachlan and retain any credits to third-parties,
# such as exterior sources for code, listed within this program.
#
# For more information, see /usr/doc/installsp/LICENSE or creativecommons.org.

version=0.1.0

# Adapted from StackOverflow; credit to Oriettaxx and Romário. URL:
# https://stackoverflow.com/questions/8063228/check-if-a-variable-exists-in-a-list-in-bash/20473191#20473191
function list_contains {
    if [[ $1 =~ (^|[[:space:]])"$2"($|[[:space:]]) ]]; then
        return 0
    else
        return 1
    fi
}

list_contains "$@" "-h" && help=1 || list_contains "$@" "--help" && help=1
list_contains "$@" "-l" && license=1 || list_contains "$@" "--license" && license=1
list_contains "$@" "-v" && call_version=1 || list_contains "$@" "--version" && call_version=1

# Show help menu / license / version
if [[ $help ]]; then
    help_text=$(< /usr/doc/installsp/help.txt)
    IFS='%'
    echo -e "$help_text"
    exit 1
elif [[ $license ]]; then
    license_text=$(< /usr/doc/installsp/LICENSE_SHORT)
    IFS='%'
    echo -e "$license_text"
    exit 1
elif [[ $call_version ]]; then
    echo "installsp: Version: $version"
    exit 1
fi

# Import config options
# shellcheck source=/dev/null
source "/usr/share/installsp/config.sh"

# Check if to upgrade an existing package
[ "$1" = "-u" ] && upgrade=1 || [ "$1" = "--upgrade" ] && upgrade=1

if [[ $upgrade && $2 && $3 ]]; then
    spname=$3
    oldp=$2
elif [[ $upgrade ]]; then
    echo "installsp: --upgrade passed, but either package name or location of new version unspecified. Run 'installsp --help' for details."
    exit 0
elif [[ $1 ]]; then
    spname=$1
else
    echo "installsp: No package specified, exiting. Run 'installsp --help' for details."
    exit 0
fi

# Read repository location from args or fall back to default from config
if [[ $upgrade && $4 ]]; then
    mvloc=$4
elif [[ ! $upgrade && $2 ]]; then
    mvloc=$2
else
    mvloc=$repository
fi

# Move and install package
if [ -f "$sploc$spname" ]; then 
    if [ -d "$mvloc" ]; then
        mv "$sploc$spname" "$mvloc$spname"
    else
        echo "installsp: Could not find directory '$mvloc', not moving package. Will still install."
    fi
    if [[ $upgrade ]]; then
        upgradepkg "$oldp" "$mvloc$spname" && echo "installsp: Upgraded package '$oldp' with '$spname'" || echo "installsp: Failed to upgrade package '$oldp' with '$spname'"
    else
        installpkg "$mvloc$spname"
        echo "installsp: Moved and installed package '$spname'"
    fi
    exit 1
else
    echo "installsp: Could not find package at: $sploc$spname"
    exit 0
fi