#!/bin/bash

# This software is provided "as-is" and without warranty.
#
# It is licensed under the Creative Commons Attribution-ShareAlike 4.0 International license.
#
# If redistributing, credit Murdo B. Maclachlan and retain any credits to third-parties,
# such as exterior sources for code, listed within this program.
#
# For more information, see /usr/doc/installsp/LICENSE or creativecommons.org.

USAGE="Usage: installsp [-hlv] -p package [-u library_to_upgrade] [-r repository]"
VERSION="0.2.0-beta"

# Import config options
source "/usr/share/installsp/config.sh"

while getopts ':hlvp:r:u:' OPTION; do
    case "$OPTION" in
        h)
            HELP=`< /usr/doc/installsp/help.txt`
            IFS='%'
            echo -e $HELP
            exit 1
            ;;
        l)
            LICENSE=`< /usr/doc/installsp/LICENSE_SHORT`
            IFS='%'
            echo -e $LICENSE
            exit 1
            ;;
        p)
            PACKAGE_NAME="$OPTARG"
            ;;
        r)
            REPOSITORY="$OPTARG"
            ;;
        u)
            UPGRADE="$OPTARG"
            ;;
        v)
            echo "installsp $VERSION"
            exit 1
            ;;
        ?)
            echo $USAGE
            exit 1
            ;;
    esac
done

if [[ -z "$PACKAGE_NAME" ]]; then
    echo "[installsp] No package provided for installation"
    echo $USAGE
    exit 1
fi

if [[ -f "$PACKAGE_LOCATION/$PACKAGE_NAME" ]]; then 

    if [[ -n "$REPOSITORY" ]]; then 
        if [[ -d "$REPOSITORY" ]]; then
            mv "$PACKAGE_LOCATION/$PACKAGE_NAME" "$REPOSITORY/$PACKAGE_NAME"
            echo "[installsp] Moved package to repository at: '$REPOSITORY'"
            PACKAGE_PATH="$REPOSITORY/$PACKAGE_NAME"
        else
            echo "[installsp] Could not find repository at '$REPOSITORY'; not moving package. Will still install."
            PACKAGE_PATH="$PACKAGE_LOCATION/$PACKAGE_NAME"
        fi
    else
        echo "[installsp] No repository given and no fallback specified in config; not moving package. Will still install."
        PACKAGE_PATH="$PACKAGE_LOCATION/$PACKAGE_NAME"
    fi

    if [[ -n "$UPGRADE" ]]; then
        upgradepkg "$UPGRADE" "$PACKAGE_PATH"
        echo "[installsp] Upgraded "$UPGRADE" with package: $PACKAGE_NAME"
    else
        installpkg "$PACKAGE_PATH"
        echo "[installsp] Installed package: $PACKAGE_NAME"
    fi
else
    echo "[installsp] Could not find package at: $PACKAGE_LOCATION/$PACKAGE_NAME"
    exit 1
fi
